agents:
  gemini:
    command: "gemini"
    append_constitution: false
    identity_targets:
      - "~/dev/space/GEMINI.md"
      - "~/dev/space/AGENTS.md"
  claude:
    command: "claude"
    append_constitution: false
    identity_targets:
      - "~/dev/space/CLAUDE.md"
      - "~/dev/space/AGENTS.md"
  codex:
    command: "codex"
    append_constitution: false
    identity_targets:
      - "~/dev/space/AGENTS.md"

roles:
  zealot:
    constitution: constitutions/zealot.md
    base_identity: claude
  
  harbinger:
    constitution: constitutions/harbinger.md
    base_identity: gemini
  
  sentinel:
    constitution: constitutions/sentinel.md
    base_identity: codex
  
  archon:
    constitution: constitutions/archon.md
    base_identity: gemini
  
  kitsuragi:
    constitution: constitutions/kitsuragi.md
    base_identity: claude
  
  prime:
    constitution: constitutions/prime.md
    base_identity: claude
