agents:
  gemini:
    command: "gemini"
    model: "gemini-2.5-pro"
    append_constitution: false
    identity_targets:
      - "~/dev/space/GEMINI.md"
      - "~/dev/space/AGENTS.md"
  claude:
    command: "claude"
    model: "claude-sonnet-4-5"
    append_constitution: false
    identity_targets:
      - "~/dev/space/CLAUDE.md"
      - "~/dev/space/AGENTS.md"
  codex:
    command: "codex"
    model: "gpt-5-codex"
    append_constitution: false
    identity_targets:
      - "~/dev/space/AGENTS.md"

roles:
  zealot:
    constitution: constitutions/zealot.md
    base_identity: claude
  
  harbinger:
    constitution: constitutions/harbinger.md
    base_identity: gemini
  
  sentinel:
    constitution: constitutions/sentinel.md
    base_identity: codex
  
  archon:
    constitution: constitutions/archon.md
    base_identity: gemini
  
  kitsuragi:
    constitution: constitutions/kitsuragi.md
    base_identity: codex
  
  prime:
    constitution: constitutions/prime.md
    base_identity: claude
  
  scribe:
    constitution: constitutions/scribe.md
    base_identity: claude

  lieutenant:
    constitution: constitutions/kitsuragi.md
    base_identity: chatgpt

  test:
    constitution: constitutions/default.md
    base_identity: claude # Assuming a default base_identity

  default:
    constitution: constitutions/default.md
    base_identity: claude
