agents:
  gemini:
    command: "gemini"
    append_constitution: false
    identity_targets:
      - "~/dev/space/GEMINI.md"
      - "~/dev/space/AGENTS.md"
  claude:
    command: "claude"
    append_constitution: false
    identity_targets:
      - "~/dev/space/CLAUDE.md"
      - "~/dev/space/AGENTS.md"
  codex:
    command: "codex"
    append_constitution: false
    identity_targets:
      - "~/dev/space/AGENTS.md"

roles:
  zealot:
    constitution: constitutions/zealot.md
    base_identity: claude
  
  harbinger:
    constitution: constitutions/harbinger.md
    base_identity: gemini
  
  sentinel:
    constitution: constitutions/sentinel.md
    base_identity: codex
  
  archon:
    constitution: constitutions/archon.md
    base_identity: gemini
  
  kitsuragi:
    constitution: constitutions/kitsuragi.md
    base_identity: claude
  
  prime:
    constitution: constitutions/prime.md
    base_identity: claude
  
  scribe:
    constitution: constitutions/scribe.md
    base_identity: claude

  lieutenant:
    constitution: constitutions/kitsuragi.md
    base_identity: chatgpt

  test:
    constitution: constitutions/default.md
    base_identity: claude # Assuming a default base_identity

  default:
    constitution: constitutions/default.md
    base_identity: claude

templates:
  minimal: |
    # {ROLE} CONSTITUTION
    
    You are {ROLE}.
    
    ## Core directive
    [Your primary purpose here]
    
    ## Principles
    - [Principle 1]
    - [Principle 2]
    
    ## Execution
    - [How you operate]
  
  researcher: |
    # RESEARCHER CONSTITUTION
    
    You are a systematic researcher.
    
    ## Core directive
    Investigate deeply, cite sources, question assumptions
    
    ## Principles
    - Evidence over intuition
    - Reproducibility matters
    - Document methodology
    
    ## Execution
    - Read broadly before concluding
    - Track hypotheses vs facts
    - Flag gaps in understanding
