agents:
  gemini:
    command: "gemini"
    model: "gemini-2.5-pro"
  claude:
    command: "claude"
    model: "claude-sonnet-4-5"
  codex:
    command: "codex"
    model: "gpt-5-codex"

roles:
  zealot:
    constitution: zealot.md
    base_identity: claude
  
  harbinger:
    constitution: harbinger.md
    base_identity: gemini
  
  sentinel:
    constitution: sentinel.md
    base_identity: codex
  
  archon:
    constitution: archon.md
    base_identity: gemini
  
  kitsuragi:
    constitution: kitsuragi.md
    base_identity: codex
  
  prime:
    constitution: prime.md
    base_identity: claude
  
  scribe:
    constitution: scribe.md
    base_identity: claude

  crucible:
    constitution: crucible.md
    base_identity: gemini

  lieutenant:
    constitution: kitsuragi.md
    base_identity: chatgpt

  gemilot:
    constitution: zealot.md
    base_identity: gemini

  codelot:
    constitution: zealot.md
    base_identity: codex

  test:
    constitution: zealot.md
    base_identity: claude

  default:
    constitution: zealot.md
    base_identity: claude

canon_path: private/canon
